###
POST http://localhost:50000/api/v1/profesor/profesor HTTP/1.1
Content-Type: application/json

{
  "client_name": "Yaneth",
  "address":[{
    "city": "Manizales",
    "code_zip":"170002",
    "geo":[{
      "lat": -4.5985,
      "long": 0.2733
    }]
  }],
  "contact":{
    "email":"ymejia@umanizales.edu.co",
    "cellphone": "3045455880"
  }
}

###
GET http://localhost:50000/api/v1/profesor HTTP/1.1
###
GET http://localhost:50000/api/v1/profesor/623d237c18d8f7c203e9f128 HTTP/1.1
###
PUT http://localhost:50000/api/v1/profesor/623d237c18d8f7c203e9f128 HTTP/1.1
Content-Type: application/json

{
  "client_name": "felipe",
  "address":[{
    "city": "pensilvania",
    "code_zip":"170004",
    "geo":[{
      "lat": -8.5985,
      "long": 0.2833
    }]
  }],
  "contact":{
    "email":"fabermudez@umanizales.edu.co",
    "cellphone": "3142405830"
  }
}

###
DELETE http://localhost:50000/api/v1/profesor/623d237c18d8f7c203e9f128 HTTP/1.1
